Repository KB-technologia/FinMate_BE, pull requests merged in 2025-07, with the labels that each got.

#13 ✨ 금융 상품 비교 API 머지 요청
  src/main/java/org/finmate/common/util/OpenAiApi.java
  src/main/java/org/finmate/common/util/OpenAiDTO/ContentItem.java
  src/main/java/org/finmate/common/util/OpenAiDTO/Format.java
  src/main/java/org/finmate/common/util/OpenAiDTO/InputTokensDetails.java
  src/main/java/org/finmate/common/util/OpenAiDTO/Metadata.java
  src/main/java/org/finmate/common/util/OpenAiDTO/OpenAiResponseDTO.java
  src/main/java/org/finmate/common/util/OpenAiDTO/OutputItem.java
  src/main/java/org/finmate/common/util/OpenAiDTO/OutputTokensDetails.java
  src/main/java/org/finmate/common/util/OpenAiDTO/Reasoning.java
  src/main/java/org/finmate/common/util/OpenAiDTO/Text.java
  src/main/java/org/finmate/common/util/OpenAiDTO/Usage.java
  src/main/java/org/finmate/config/RootConfig.java
  src/main/java/org/finmate/product/controller/ProductController.java
  src/main/java/org/finmate/product/dto/ProductComparisonResultDTO.java
  src/main/java/org/finmate/product/dto/ProductDTO.java
  src/main/java/org/finmate/product/service/ProductService.java
  src/main/java/org/finmate/product/service/ProductServiceImpl.java
Labels: enhancement

#16 🔨 REST기반 Exception handler 생성 머지 요청
  src/main/java/org/finmate/exception/CommonExceptionAdvice.java
  src/main/java/org/finmate/exception/ErrorResponse.java
  src/main/webapp/WEB-INF/views/custom404.jsp
  src/main/webapp/WEB-INF/views/error_page.jsp
  src/main/webapp/WEB-INF/views/index.jsp
Labels: documentation, enhancement

#19 ✨ 상품 전체 보기 API 개발 머지 요청
  src/main/java/org/finmate/product/controller/ProductController.java
  src/main/java/org/finmate/product/mapper/ProductMapper.java
  src/main/java/org/finmate/product/service/ProductService.java
  src/main/java/org/finmate/product/service/ProductServiceImpl.java
  src/main/resources/org/finmate/product/mapper/ProductMapper.xml
Labels: enhancement

#21 ✨ 회원가입 API 구현
  src/main/java/org/finmate/config/RootConfig.java
  src/main/java/org/finmate/config/ServletConfig.java
  src/main/java/org/finmate/member/controller/SignupController.java
  src/main/java/org/finmate/member/domain/Provider.java
  src/main/java/org/finmate/member/domain/UserVO.java
  src/main/java/org/finmate/member/dto/SignupRequestDTO.java
  src/main/java/org/finmate/member/mapper/UserMapper.java
  src/main/java/org/finmate/member/service/SignupService.java
  src/main/resources/mybatis-config.xml
  src/main/resources/org/finmate/member/mapper/UserMapper.xml
Labels: enhancement

#28 ✨일반 로그인 기능 구현
  build.gradle
  src/main/java/org/finmate/auth/controller/SecurityController.java
  src/main/java/org/finmate/auth/domain/CustomUser.java
  src/main/java/org/finmate/auth/domain/LoginProvider.java
  src/main/java/org/finmate/auth/domain/UserVO.java
  src/main/java/org/finmate/auth/mapper/UserMapper.java
  src/main/java/org/finmate/auth/service/CustomUserDetailsService.java
  src/main/java/org/finmate/config/RootConfig.java
  src/main/java/org/finmate/config/ServletConfig.java
  src/main/java/org/finmate/config/WebConfig.java
  src/main/java/org/finmate/security/config/EncoderConfig.java
  src/main/java/org/finmate/security/config/SecurityConfig.java
  src/main/java/org/finmate/security/config/SecurityInitializer.java
  src/main/java/org/finmate/security/dto/AuthResultDTO.java
  src/main/java/org/finmate/security/dto/LoginDTO.java
  src/main/java/org/finmate/security/dto/UserInfoDTO.java
  src/main/java/org/finmate/security/filter/AuthenticationErrorFilter.java
  src/main/java/org/finmate/security/filter/JwtAuthenticationFilter.java
  src/main/java/org/finmate/security/filter/JwtUsernamePasswordAuthenticationFilter.java
  src/main/java/org/finmate/security/handler/CustomAccessDeniedHandler.java
  src/main/java/org/finmate/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/org/finmate/security/handler/LoginFailureHandler.java
  src/main/java/org/finmate/security/handler/LoginSuccessHandler.java
  src/main/java/org/finmate/security/handler/LogoutSuccessHandlerImpl.java
  src/main/java/org/finmate/security/util/JsonResponse.java
  src/main/java/org/finmate/security/util/JwtProcessor.java
  src/main/resources/mybatis-config.xml
  src/main/resources/org/finmate/auth/mapper/MapperTemplate.xml
  src/main/resources/org/finmate/auth/mapper/UserMapper.xml
  src/test/java/org/finmate/security/config/EncoderConfigTest.java
Labels: enhancement

#32 ♻️ 시큐리티 및 전체적인 리팩토링, 예외 추가
  .github/workflows/gradle.yml
  src/main/java/org/finmate/assessment/dto/AssessmentDTO.java
  src/main/java/org/finmate/assessment/dto/AssessmentDetailsDTO.java
  src/main/java/org/finmate/assessment/service/AssessmentServiceImpl.java
  src/main/java/org/finmate/auth/controller/SecurityController.java
  src/main/java/org/finmate/auth/domain/LoginProvider.java
  src/main/java/org/finmate/auth/domain/UserVO.java
  src/main/java/org/finmate/auth/mapper/UserMapper.java
  src/main/java/org/finmate/controller/HomeController.java
  src/main/java/org/finmate/exception/CommonExceptionAdvice.java
  src/main/java/org/finmate/exception/NotFoundException.java
  src/main/java/org/finmate/mapper/TimeMapper.java
  src/main/java/org/finmate/member/controller/MyPageController.java
  src/main/java/org/finmate/member/domain/CustomUser.java
  src/main/java/org/finmate/member/domain/UserVO.java
  src/main/java/org/finmate/member/dto/AnimalCharacterDTO.java
  src/main/java/org/finmate/member/dto/MyPageResponseDTO.java
  src/main/java/org/finmate/member/dto/MyPageUpdateRequestDTO.java
  src/main/java/org/finmate/member/dto/UserInfoDTO.java
  src/main/java/org/finmate/member/mapper/UserMapper.java
  src/main/java/org/finmate/member/service/AnimalCharacterServiceImpl.java
  src/main/java/org/finmate/member/service/CustomUserDetailsService.java
  src/main/java/org/finmate/member/service/MyPageService.java
  src/main/java/org/finmate/member/service/SignupService.java
  src/main/java/org/finmate/portfolio/dto/PortfolioDTO.java
  src/main/java/org/finmate/portfolio/service/PortfolioServiceImpl.java
  src/main/java/org/finmate/product/dto/ProductReviewDTO.java
  src/main/java/org/finmate/product/service/ProductServiceImpl.java
  src/main/java/org/finmate/quiz/dto/QuizDTO.java
  src/main/java/org/finmate/quiz/service/QuizServiceImpl.java
  src/main/java/org/finmate/security/config/SecurityConfig.java
  src/main/java/org/finmate/security/dto/UserInfoDTO.java
  src/main/java/org/finmate/security/handler/LoginSuccessHandler.java
  src/main/resources/org/finmate/auth/mapper/MapperTemplate.xml
  src/main/resources/org/finmate/auth/mapper/UserMapper.xml
  src/main/resources/org/finmate/member/mapper/UserMapper.xml
Labels: enhancement, refactor

#35 ♻️MyBatis Optional 처리 관련 로직 수정
  src/main/java/org/finmate/product/mapper/ProductMapper.java
  src/main/java/org/finmate/product/service/ProductServiceImpl.java
  src/main/java/org/finmate/quiz/mapper/QuizMapper.java
  src/main/java/org/finmate/quiz/service/QuizServiceImpl.java
Labels: enhancement, refactor

#36 ✨ 금융 상품 리뷰 추가 기능 개발
  build.gradle
  src/main/java/org/finmate/product/controller/ProductController.java
  src/main/java/org/finmate/product/mapper/ProductMapper.java
  src/main/resources/org/finmate/product/mapper/ProductMapper.xml
Labels: bug, enhancement

#39 ✨ 이메일 인증 API 구현
  build.gradle
  src/main/java/org/finmate/common/util/MailConfig.java
  src/main/java/org/finmate/config/RootConfig.java
  src/main/java/org/finmate/member/controller/EmailAuthController.java
  src/main/java/org/finmate/member/controller/MyPageController.java
  src/main/java/org/finmate/member/domain/EmailAuthVO.java
  src/main/java/org/finmate/member/dto/EmailRequestDTO.java
  src/main/java/org/finmate/member/dto/EmailVerifyRequestDTO.java
  src/main/java/org/finmate/member/dto/SignupRequestDTO.java
  src/main/java/org/finmate/member/mapper/EmailAuthMapper.java
  src/main/java/org/finmate/member/mapper/UserMapper.java
  src/main/java/org/finmate/member/service/EmailAuthService.java
  src/main/java/org/finmate/member/service/MemberService.java
  src/main/java/org/finmate/member/service/SignupService.java
  src/main/resources/org/finmate/member/mapper/EmailAuthMapper.xml
  src/main/resources/org/finmate/member/mapper/UserMapper.xml
Labels: enhancement

#40 ✨즐겨찾기 API 머지 요청
  src/main/java/org/finmate/exception/CommonExceptionAdvice.java
  src/main/java/org/finmate/product/controller/FavoriteController.java
  src/main/java/org/finmate/product/domain/FavoriteVO.java
  src/main/java/org/finmate/product/dto/FavoriteDTO.java
  src/main/java/org/finmate/product/mapper/ProductMapper.java
  src/main/java/org/finmate/product/service/FavoriteService.java
  src/main/java/org/finmate/product/service/FavoriteServiceImpl.java
  src/main/resources/org/finmate/product/mapper/ProductMapper.xml
Labels: enhancement

#43 :sparkles: 새로운 VO 생성 및 데이터 구조 수정
  src/main/java/org/finmate/product/domain/ProductRateVO.java
  src/main/java/org/finmate/product/domain/ProductVO.java
  src/main/java/org/finmate/product/dto/ProductDTO.java
  src/main/resources/org/finmate/product/mapper/ProductMapper.xml
Labels: enhancement

#44 ♻️ 투자 성향 진단 테스트 API 사용자 ID 요청 방식 변경
  src/main/java/org/finmate/assessment/controller/AssessmentController.java
  src/main/java/org/finmate/assessment/dto/AssessmentRequestDTO.java
Labels: refactor

#45 ♻️ 캐릭터 API 사용자 ID 요청 방식 변경
  src/main/java/org/finmate/member/controller/AnimalCharacterController.java
  src/main/java/org/finmate/member/dto/AnimalChangeDTO.java
Labels: refactor

#47 ✨ 예적금 칼럼 및 VO 수정
  src/main/java/org/finmate/product/domain/DepositVO.java
  src/main/java/org/finmate/product/domain/PaymentCycle.java
  src/main/java/org/finmate/product/domain/ProductVO.java
  src/main/java/org/finmate/product/domain/SavingsVO.java
  src/main/java/org/finmate/product/dto/ProductDTO.java
  src/main/resources/org/finmate/product/mapper/ProductMapper.xml
Labels: enhancement

#48 :sparkles: : 일반 로그인 CorsFilter 설정 추가
  src/main/java/org/finmate/security/config/SecurityConfig.java
Labels: enhancement

#52 ✨ 카카오 로그인 API 연동 및 프론트 리다이렉트 처리
  src/main/java/org/finmate/member/controller/KakaoAuthController.java
Labels: duplicate, enhancement

#53 ✨ 회원탈퇴, 아이디찾기/비밀번호변경
  src/main/java/org/finmate/config/RootConfig.java
  src/main/java/org/finmate/member/controller/AccountRecoveryController.java
  src/main/java/org/finmate/member/controller/EmailAuthController.java
  src/main/java/org/finmate/member/controller/MyPageController.java
  src/main/java/org/finmate/member/controller/SignupController.java
  src/main/java/org/finmate/member/dto/ChangePasswordRequestDTO.java
  src/main/java/org/finmate/member/dto/EmailAuthInitResponseDTO.java
  src/main/java/org/finmate/member/dto/FindAccountIdRequestDTO.java
  src/main/java/org/finmate/member/dto/FindAccountIdResponseDTO.java
  src/main/java/org/finmate/member/dto/VerifyUserRequestDTO.java
  src/main/java/org/finmate/member/mapper/EmailAuthMapper.java
  src/main/java/org/finmate/member/mapper/UserMapper.java
  src/main/java/org/finmate/member/service/AccountRecoveryService.java
  src/main/java/org/finmate/member/service/SignupService.java
  src/main/java/org/finmate/security/config/SecurityConfig.java
  src/main/resources/org/finmate/member/mapper/EmailAuthMapper.xml
  src/main/resources/org/finmate/member/mapper/UserMapper.xml
Labels: enhancement

#54 ✨ 사용자 리뷰 조회 API 개발
  src/main/java/org/finmate/member/controller/MyPageController.java
  src/main/java/org/finmate/product/mapper/ProductMapper.java
  src/main/java/org/finmate/product/service/ProductService.java
  src/main/java/org/finmate/product/service/ProductServiceImpl.java
  src/main/java/org/finmate/security/config/SecurityConfig.java
  src/main/resources/org/finmate/product/mapper/ProductMapper.xml
Labels: enhancement

#60 ♻️ 멤버서비스, 마이페이지컨트롤러(accountId -> userId)
  src/main/java/org/finmate/member/controller/MyPageController.java
  src/main/java/org/finmate/member/controller/SignupController.java
  src/main/java/org/finmate/member/domain/UserInfoVO.java
  src/main/java/org/finmate/member/domain/UserVO.java
  src/main/java/org/finmate/member/domain/enums/AnniversaryFrequency.java
  src/main/java/org/finmate/member/domain/enums/Gender.java
  src/main/java/org/finmate/member/domain/enums/HousingType.java
  src/main/java/org/finmate/member/domain/enums/MaritalStatus.java
  src/main/java/org/finmate/member/domain/enums/TravelFrequency.java
  src/main/java/org/finmate/member/dto/SignupRequestDTO.java
  src/main/java/org/finmate/member/service/MemberService.java
  src/main/java/org/finmate/member/service/SignupService.java
  src/main/resources/org/finmate/member/mapper/UserInfoMapper.xml
  src/main/resources/org/finmate/member/mapper/UserMapper.xml
Labels: enhancement

#62 ✨ 랜덤 금융상품 추천 조회 API 머지 요청
  src/main/java/org/finmate/product/controller/ProductRecommendationController.java
  src/main/java/org/finmate/product/mapper/ProductMapper.java
  src/main/resources/org/finmate/product/mapper/ProductMapper.xml
Labels: enhancement

#67 ✨ 카카오 로그인 사용자 정보 추가
  src/main/java/org/finmate/member/controller/KakaoAuthController.java
  src/main/java/org/finmate/member/domain/KakaoUser.java
  src/main/java/org/finmate/member/dto/KakaoUserResponse.java
  src/main/java/org/finmate/member/service/KakaoService.java
  src/main/java/org/finmate/security/dto/AuthResultDTO.java
  src/main/java/org/finmate/security/dto/UserLoginInfoDTO.java
  src/main/java/org/finmate/security/handler/LoginSuccessHandler.java
Labels: refactor

#69 ♻️ 일일 금융 퀴즈 정답 검증 로직 수정
  src/main/java/org/finmate/quiz/controller/QuizController.java
  src/main/java/org/finmate/quiz/dto/QuizAnswerResponseDTO.java
  src/main/java/org/finmate/quiz/service/QuizService.java
  src/main/java/org/finmate/quiz/service/QuizServiceImpl.java
Labels: refactor

#73 ♻️칼럼명 변경
  src/main/java/org/finmate/member/domain/UserInfoVO.java
  src/main/java/org/finmate/member/domain/enums/AnniversaryFrequency.java
  src/main/java/org/finmate/member/domain/enums/HousingType.java
  src/main/java/org/finmate/member/domain/enums/MaritalStatus.java
  src/main/java/org/finmate/member/domain/enums/TravelFrequency.java
  src/main/java/org/finmate/member/dto/SignupRequestDTO.java
  src/main/java/org/finmate/member/service/SignupService.java
  src/main/resources/org/finmate/member/mapper/UserInfoMapper.xml
Labels: enhancement

#76 :sparkles: AI 프롬프트 수정
  src/main/java/org/finmate/adapter/openbank/FinancialProductApi.java
  src/main/java/org/finmate/exception/CommonExceptionAdvice.java
  src/main/java/org/finmate/member/domain/UserInfoVO.java
  src/main/java/org/finmate/portfolio/domain/PortfolioVO.java
  src/main/java/org/finmate/product/domain/ProductVO.java
  src/main/java/org/finmate/product/service/ProductServiceImpl.java
  src/main/resources/prompts/product_compare.txt
  src/main/resources/prompts/product_recommend.txt
Labels: enhancement
