Repository KB-technologia/FinMate_BE, pull requests merged in 2025-08, with the labels that each got.

#77 :sparkles: 금융 상품 리뷰 등록 수정
  src/main/java/org/finmate/product/controller/ProductController.java
  src/main/java/org/finmate/product/mapper/ProductMapper.java
  src/main/java/org/finmate/product/service/ProductService.java
  src/main/java/org/finmate/product/service/ProductServiceImpl.java
  src/main/resources/org/finmate/product/mapper/ProductMapper.xml
Labels: enhancement

#78 ✨ 캐릭터 API 로직 수정 및 머지 요청
  src/main/java/org/finmate/member/controller/AnimalCharacterController.java
  src/main/java/org/finmate/member/domain/UserInfoVO.java
  src/main/java/org/finmate/member/dto/AnimalCharacterDTO.java
  src/main/java/org/finmate/member/dto/UserInfoDTO.java
  src/main/java/org/finmate/member/service/AnimalCharacterServiceImpl.java
  src/main/resources/org/finmate/member/mapper/UserInfoMapper.xml
  src/main/webapp/resources/고양이1.png
  src/main/webapp/resources/래서판다1.png
  src/main/webapp/resources/사막여우1.png
  src/main/webapp/resources/카피바라1.png
  src/main/webapp/resources/코알라1.png
  src/main/webapp/resources/키위새1.png
  src/main/webapp/resources/팬더1.png
  src/main/webapp/resources/펭귄1.png
  src/main/webapp/resources/하늘다람쥐1.png
  src/main/webapp/resources/해달1.png
Labels: enhancement

#79 ✨ 투자 성향 테스트 API 로직 수정 및 머지 요청
  src/main/java/org/finmate/assessment/service/AssessmentServiceImpl.java
  src/main/resources/org/finmate/member/mapper/UserInfoMapper.xml
Labels: enhancement

#84 ✨ 사용자 가입 상품 조회 API 구현
  src/main/java/org/finmate/member/controller/MyProductsController.java
Labels: enhancement

#80 ✨ 카카오 로그인 신규 회원 정보 + 설문 응답 통합 처리
  src/main/java/org/finmate/member/dto/SignupRequestDTO.java
  src/main/java/org/finmate/member/service/KakaoService.java
  src/main/java/org/finmate/member/service/SignupService.java
  src/main/java/org/finmate/security/dto/UserLoginInfoDTO.java
Labels: bug, enhancement

#86 ♻️재무 포트폴리오 검색 조건 변경
  src/main/java/org/finmate/adapter/mydata/dto/MyDataProductDTO.java
  src/main/java/org/finmate/adapter/mydata/dto/MyDataResponseDTO.java
  src/main/java/org/finmate/portfolio/controller/PortfolioController.java
  src/main/java/org/finmate/portfolio/dto/PortfolioDTO.java
  src/main/java/org/finmate/portfolio/mapper/PortfolioMapper.java
  src/main/java/org/finmate/portfolio/service/PortfolioService.java
  src/main/java/org/finmate/portfolio/service/PortfolioServiceImpl.java
  src/main/resources/org/finmate/portfolio/mapper/PortfolioMapper.xml
Labels: refactor

#87 ♻️ findAccountIdByUuid 응답에 name 포함되도록 수정
  src/main/java/org/finmate/member/controller/AccountRecoveryController.java
  src/main/java/org/finmate/member/dto/FindAccountIdResponseDTO.java
  src/main/java/org/finmate/member/mapper/UserMapper.java
  src/main/java/org/finmate/member/service/AccountRecoveryService.java
  src/main/resources/org/finmate/member/mapper/UserMapper.xml
Labels: enhancement

#88 ✨ 사용자 투자성향 기반 금융상품 추천 기능 머지 요청
  src/main/java/org/finmate/member/dto/UserInfoDTO.java
  src/main/java/org/finmate/product/controller/ProductRecommendationController.java
  src/main/java/org/finmate/product/service/ProductService.java
  src/main/java/org/finmate/product/service/ProductServiceImpl.java
Labels: enhancement

#93 ✨ 데이터베이스 엔드포인트 수정 및 RDS연동
  src/main/java/org/finmate/member/controller/MyPageController.java
  src/main/resources/application.properties
  src/main/resources/prompts/product_recommend.txt
Labels: documentation, enhancement

#95 ✨ 추천 로직 수정 및 머지 요청
  src/main/java/org/finmate/product/controller/ProductRecommendationController.java
  src/main/java/org/finmate/product/service/ProductServiceImpl.java
Labels: enhancement

#96 ✨ 로그인 출석체크 API 개발
  src/main/java/org/finmate/attendance/controller/UserAttendanceController.java
  src/main/java/org/finmate/attendance/domain/UserAttendanceVO.java
  src/main/java/org/finmate/attendance/dto/UserAttendanceDTO.java
  src/main/java/org/finmate/attendance/mapper/UserAttendanceMapper.java
  src/main/java/org/finmate/attendance/service/UserAttendanceService.java
  src/main/java/org/finmate/attendance/service/UserAttendanceServiceImpl.java
  src/main/java/org/finmate/config/RootConfig.java
  src/main/java/org/finmate/config/ServletConfig.java
  src/main/java/org/finmate/member/service/KakaoService.java
  src/main/java/org/finmate/security/dto/AuthResultDTO.java
  src/main/java/org/finmate/security/handler/LoginSuccessHandler.java
  src/main/resources/org/finmate/attendance/mapper/UserAttendanceMapper.xml
Labels: enhancement

#99 🔨 상품 목록 JSON과 상품 목록 받아오는 메서드 수정
  src/main/java/org/finmate/adapter/openbank/FinancialProductApi.java
  src/main/resources/dummy/products/financial_products.json
Labels: enhancement, refactor

#103 🐛 사용자 출석값이 널일경우 로그인이 안되는 버그 수정
  src/main/java/org/finmate/config/RootConfig.java
  src/main/java/org/finmate/security/handler/LoginSuccessHandler.java
Labels: bug

#101 ✨ 경험치 및 레벨 업 API 머지 요청
  src/main/java/org/finmate/member/controller/LevelController.java
  src/main/java/org/finmate/member/dto/LevelRequestDTO.java
  src/main/java/org/finmate/member/dto/LevelResponseDTO.java
  src/main/java/org/finmate/member/service/LevelService.java
  src/main/java/org/finmate/member/service/LevelServiceImpl.java
Labels: enhancement

#105 🐛 상품 추천 API 수정 및 머지 요청
  src/main/java/org/finmate/product/service/ProductServiceImpl.java
Labels: enhancement

#107 ✨ 일일 금융 퀴즈 검증 로직 추가
  src/main/java/org/finmate/attendance/domain/UserAttendanceVO.java
  src/main/java/org/finmate/attendance/mapper/UserAttendanceMapper.java
  src/main/java/org/finmate/quiz/controller/QuizSolvedController.java
  src/main/java/org/finmate/quiz/dto/QuizSolvedDTO.java
  src/main/java/org/finmate/quiz/service/QuizService.java
  src/main/java/org/finmate/quiz/service/QuizServiceImpl.java
  src/main/resources/org/finmate/attendance/mapper/UserAttendanceMapper.xml
Labels: enhancement

#112 ♻️ 회원가입 시 레벨,티켓 기본값 넣기
  src/main/java/org/finmate/member/service/MemberServiceImpl.java
Labels: enhancement

#110 📚 금융 상품 adventureScore 값 수정
  src/main/resources/dummy/products/financial_products.json
Labels: documentation

#115 ✨ 추천 로직 보완
  src/main/java/org/finmate/product/domain/ProductVO.java
  src/main/java/org/finmate/product/dto/ProductDTO.java
  src/main/java/org/finmate/product/service/ProductServiceImpl.java
Labels: enhancement

#116 🐛 회원 탈퇴 버그 수정
  src/main/java/org/finmate/member/mapper/UserMapper.java
  src/main/java/org/finmate/member/service/MemberServiceImpl.java
  src/main/resources/org/finmate/member/mapper/UserMapper.xml
Labels: enhancement

#119 🐛 회원탈퇴 버그 수정(즐겨찾기 테이블 삭제)
  src/main/java/org/finmate/member/mapper/UserMapper.java
  src/main/java/org/finmate/member/service/MemberServiceImpl.java
  src/main/resources/org/finmate/member/mapper/UserMapper.xml
Labels: enhancement

#127 ♻️ 마이데이터 보유 상품 연동
  src/main/java/org/finmate/adapter/mydata/dto/MyDataProductDTO.java
  src/main/resources/dummy/mydata/user_financial_products.json
  src/main/resources/dummy/products/financial_products.json
Labels: enhancement

#132 ✨ CharacterResponseDTO 캐릭터 ID 필드 추가
  src/main/java/org/finmate/character/dto/CharacterResponseDTO.java
  src/main/java/org/finmate/character/service/CharacterServiceImpl.java
Labels: enhancement

#131 🐛 금융 상품 비교 에러 수정
  src/main/java/org/finmate/product/service/ProductServiceImpl.java
  src/main/resources/application.properties
Labels: bug

#135 ✨ 금융 상품 상세보기 AI 추가
  src/main/java/org/finmate/product/controller/ProductController.java
  src/main/java/org/finmate/product/dto/ProductDTO.java
  src/main/java/org/finmate/product/service/ProductService.java
  src/main/java/org/finmate/product/service/ProductServiceImpl.java
  src/main/resources/prompts/product_recommend.txt
Labels: enhancement

#136 ✨ 추천 로직 수정
  src/main/java/org/finmate/product/service/ProductServiceImpl.java
Labels: enhancement

#138 ✨ API 응답 정리 및 문서화 보강
  src/main/java/org/finmate/attendance/dto/UserAttendanceDTO.java
  src/main/java/org/finmate/common/controller/HealthController.java
  src/main/java/org/finmate/member/controller/LevelController.java
  src/main/java/org/finmate/member/dto/SignupRequestDTO.java
  src/main/java/org/finmate/mypage/dto/UserStatResponseDTO.java
  src/main/java/org/finmate/product/controller/ProductController.java
  src/main/java/org/finmate/product/dto/ProductDTO.java
  src/main/java/org/finmate/product/service/ProductService.java
  src/main/java/org/finmate/product/service/ProductServiceImpl.java
  src/main/java/org/finmate/quiz/controller/QuizController.java
  src/main/java/org/finmate/quiz/controller/QuizSolvedController.java
  src/main/java/org/finmate/quiz/dto/QuizSolvedDTO.java
  src/main/resources/prompts/product_recommend.txt
Labels: enhancement

#139 ✨ 전체 상품 페이지에 수익률, 최신순 정렬 추가
  src/main/java/org/finmate/product/service/ProductServiceImpl.java
Labels: enhancement
